import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#101014',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  formContainer: {
    alignItems: 'center',
    width: '100%',
  },
  logoWrapper: {
    width: 82,
    height: 82,
    borderRadius: 14,
    backgroundColor: '#1C1C22',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#282832',
    overflow: 'hidden', // <-- Essencial para a imagem não vazar as bordas arredondadas
    shadowColor: '#E50914',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  logoImage: {
    width: '100%',
    height: '100%',
  },
  logoText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FFFFFF',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  logoAccent: {
    color: '#E50914',
  },
  subtitle: {
    fontSize: 13,
    color: '#8E8E93',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 18,
    paddingHorizontal: 10,
  },
  input: {
    width: '100%',
    height: 52,
    backgroundColor: '#1C1C22',
    borderRadius: 12,
    paddingHorizontal: 16,
    color: '#FFFFFF',
    marginBottom: 14,
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#282832',
  },
  loginButton: {
    width: '100%',
    height: 52,
    backgroundColor: '#E50914',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    shadowColor: '#E50914',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  loginButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 0.5,
  },
});